/**
 * Summarizer Service
 *
 * Handles summarization of bundles. Supports stub mode for testing
 * and real LLM mode via callLlm().
 *
 * Spec references: 7.4 (Process), 6.10 (Output)
 */

import { prisma } from '../db'
import { estimateTokens } from './bundle'
import { callLlm, inferProvider } from '../llm'
import type { LlmRequest } from '../llm'

export interface SummarizeOptions {
  bundleText: string
  model: string
  promptVersionId: string
}

export interface SummarizeResult {
  text: string
  tokensIn: number
  tokensOut: number
  costUsd: number
}

/**
 * Summarizes a bundle using the specified model.
 *
 * For stub models (stub_summarizer_v1), returns a deterministic stub response.
 * For real models (gpt-4o, claude-sonnet-4-5, etc.), calls the LLM API via callLlm().
 */
export async function summarize(options: SummarizeOptions): Promise<SummarizeResult> {
  const { bundleText, model, promptVersionId } = options

  // Get prompt template
  const promptVersion = await prisma.promptVersion.findUnique({
    where: { id: promptVersionId },
  })
  if (!promptVersion) {
    throw new Error(`PromptVersion not found: ${promptVersionId}`)
  }

  // Check if stub mode
  if (model.startsWith('stub')) {
    return stubSummarize(bundleText, model)
  }

  // Real LLM mode: call provider via callLlm()
  const provider = inferProvider(model)
  const req: LlmRequest = {
    provider,
    model,
    system: promptVersion.templateText,
    messages: [{ role: 'user', content: bundleText }],
    metadata: { stage: 'summarize' },
  }

  const resp = await callLlm(req)

  return {
    text: resp.text,
    tokensIn: resp.tokensIn,
    tokensOut: resp.tokensOut,
    costUsd: resp.costUsd,
  }
}

/**
 * Stub summarizer for testing.
 * Returns a deterministic summary based on the bundle content.
 */
function stubSummarize(bundleText: string, model: string): SummarizeResult {
  const inputTokens = estimateTokens(bundleText)

  // Extract some stats from the bundle
  const lines = bundleText.split('\n')
  const sourceHeaders = lines.filter((l) => l.startsWith('# SOURCE:')).length
  const messageLines = lines.filter((l) => l.match(/^\[.*?\] (user|assistant):/)).length

  // Build stub summary
  const summary = `## Summary (stub)

This is a **stub summary** generated by \`${model}\`.

### Statistics
- **Sources**: ${sourceHeaders}
- **Messages**: ${messageLines}
- **Input tokens** (estimated): ${inputTokens}

### Content Overview
The bundle contains ${messageLines} messages from ${sourceHeaders} source(s).

*Note: This is a deterministic stub for testing. Real summarization will use an LLM.*`

  const outputTokens = estimateTokens(summary)

  return {
    text: summary,
    tokensIn: inputTokens,
    tokensOut: outputTokens,
    // Stub cost: 0
    costUsd: 0,
  }
}

/**
 * Gets the active summarize prompt version.
 */
export async function getActiveSummarizePromptVersion() {
  return prisma.promptVersion.findFirst({
    where: {
      isActive: true,
      prompt: { stage: 'SUMMARIZE' },
    },
    include: {
      prompt: true,
    },
  })
}
